[package]
name = "half-cloud/ecr-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ecr = "centau/ecr@0.8.0"
t = "osyrisrblx/t@3.1.1"

[server-dependencies]
lapis = "nezuo/lapis@0.3.3"
