[package]
name = "half-cloud/ecr-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ecr = "centau/ecr@0.9.0"
t = "osyrisrblx/t@3.1.1"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[server-dependencies]
skilift = "alicesaidhi/skilift@0.3.0"
